### ISSUE TITLE
Request Count decreases during orchestration over time

### ISSUE THREAD

**Issue by Khadgar** [Azure/azure-functions-durable-js#212]
**Describe the bug**
I am using the [Fan-out/fan-in scenario in Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-cloud-backup?tabs=javascript) pattern to process ~230k blobs.
At the beginning I have high request count (~600) but over time it decreases to a lower (~30) count. See the attached picture it shows how the request count decreased over time.
![request_count_decrease](https://user-images.githubusercontent.com/483469/89934934-30fb3b00-dbc6-11ea-9771-d817bcf72a50.PNG)

**Investigative information**

- Azure Functions runtime version (1.0 or 2.0): **2.0**
- durable-functions npm module version: **1.4.3**
- Language (JavaScript/TypeScript) and version: **Typescript version 3.9.5**
- Node.js version: **v10.14.1**
 
***If deployed to Azure App Service***

- Timeframe issue observed: **6:00 PM 08/10/2020 - 4:00 AM 08/11/2020** 
- Function App name: **empowermddatastorage-stab**
- Function name(s): Orchestration function: **datasetIngress Activity function: a_ingressContainer**
- Region: **West US 2**
- Orchestration instance ID(s): **79557155-c4eb-4853-8259-546ef6a78262**

**To Reproduce**
It happens all the time when I start the orchestration for this amount of data.

**host.json**
```
{
    "version": "2.0",
    "functionTimeout": "00:10:00",
    "extensions": {
        "durableTask": {
            "maxConcurrentActivityFunctions": 4
        }
    }
}
```
App service plan: **ASP-empowermddatastoragestab-b2fr (EP1: 1)**

**Expected behavior**
To have high request count all the time during the orchestration.

**Actual behavior**
Request count decreases over time during the orchestration 

**Additional context**

- Development environment Visual Studio Code

**Comment by davidmrdavid** [comment]
Hey @Khadgar,

Thank you for reaching out! Do you mind clarifying what you mean by "requests count" in this context. Is that, perhaps, the executions of orchestrations doing the fan-in? Please let us know, and please let us know if you have a minimal reproducer we could borrow to debug this. Thanks!

⚡ ⚡

**Comment by davidmrdavid** [comment]
A larger (and appropiately anonymized) screenshot of the plot you uploaded may also help us understand its context. What is the name of this plot and where can one find it? That would help us out too. Thanks again!

**Comment by Khadgar** [comment]
Hey @davidmrdavid 

Here is a screenshot from the same timeframe. It is from `Azure > Application Insights > Failures`
This request count is the fan-in executions. At the beginning of the orchestration it is high and by time it decreases.

The orchestration code I was using is following the logic which is in the documentation I linked at the original post.

![image](https://user-images.githubusercontent.com/483469/90673835-20be0e00-e20d-11ea-90d9-b17f0fbe17f5.png)

**Comment by davidmrdavid** [comment]
Hi @Khadgar ,

Thank you providing this screenshot. I took a look at our internal records and I'm seeing some warnings being raised for your `a_ingressContainer` Activity call. In particular, it appears that it might contain a "Bad Async Function Pattern", meaning that you may  have written asynchronous code in one of your functions that continues  to run after its entry point function is known to be  completed. 

It is likely that an asynchronouos call is not awaited, or something of the like. Could you give that a look? Those issues can create scalability problems.

However, that doesn't necessarily fully explain this issue. There was also known issue in Durable-Extension v1.x where a large history of activities created a quadratic penalty on our logging cost. This issue is fixed when choosing Durable-Extension v2.x, which I think should be available via extension bundles already or very soon. Let me get back to you this, but we suspect this may be responsible for your issue.

**Comment by davidmrdavid** [comment]
Hi again @Khadgar ,

I was trying to dig a little deeper on this today, but our internal logs did not match your screenshot. We suspect its because we may be looking at the wrong timezone interpretation of your screenshot. Could you provide us with a time-range in UTC time?

Thanks!

**Comment by Khadgar** [comment]
Hey @davidmrdavid 

Thank you for looking into the problem.

My local timezone is: PST I could get the timerange in UTC:
2020-08-11T01:28:24.2292377Z - 2020-08-11T10:41:56.1594721Z

In the meantime I've updated DurableTask to version 2.2.2 It is a little bit better but I can still experience this request count decrease over time. The best explanation for this behavior maybe (but not so technical) is "Durable tasks are really fast at the beginning but over time they are slowing down".

**Comment by davidmrdavid** [comment]
Hi @Khadgar ,

Thank you for the time range, I'm able to see decreasing parallelism as well now. However, this was an error with Durable-Extension v1.x, which had a known issue around logging with long histories.

However, if you're seeing something like this with Durable-Extension v2.x, then that may be worth investigating. Can you send a UTC timerange for that and another anonymized picture of what you're seeing in the portal graph? Thank you

**Comment by davidmrdavid** [comment]
Hey @Khadgar ,

Just another follow-up. I checked with my colleagues and they suspect this may be because we don't have [extended sessions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions) available for Durable Functions JS, which prevents us from doing some optimizations during long-running orchestrations.

Moving forward, one approach you could take is to ramp up the pending orchestration message count, which allows for bigger batches of messages per fan-in, leading to less duplicate work overall. You would still likely see a decrease in the number of fan-ins over time, but increasing that from 256 to the max of 1000 would at least cut the number of fan-ins by a factor of 4.

Other than that, we have an internal issue filed to make this a priority improvement, so we'll look into improving the JS (and Python) performance on long running workloads. I hope that makes sense, and thank you for your understanding :)

**Comment by Khadgar** [comment]
Hey @davidmrdavid ,

Thank you for replying!
Yeah I tried extended sessions before because I've read that it could be my solution but it didn't work for Durable Functions JS :( I hope it will in the near future.
Could you please tell me how can I ramp up the pending orchestration message count?

Thanks,
Daniel

**Comment by davidmrdavid** [comment]
@Khadgar 

Of course! Please read this link: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#hostjson-settings

In particular, we were suggesting that you play with increasing `controlQueueBufferThreshold`, which is described in the link above :)

**Comment by davidmrdavid** [comment]
Note that it comes with a memory consumption cost, so it's a trade-off.

**Comment by Khadgar** [comment]
@davidmrdavid 
I am just wondering, do you have an estimation for the `extended sessions` support for Durable Functions JS?

**Comment by davidmrdavid** [comment]
I believe we're currently trying to incorporate the necessary internal changes in the next version of durable-extension. We're currently doing some experimentation to find this out but, if everything goes well, it could be sometime in the next two months!
